### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ament/ament_index#49]
This issue tracks the progression of packages in `ament_index` that have been deemed necessary for Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/rep-2004/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- ament_index_cpp

Excluded for Quality Level 1 at this time:
- ament_index_python

# Progress of ament_index_cpp:
* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Recommended guidelines for ROS Core packages in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#package-requirements)
* [x] API and ABI stability within a ROS distribution
* [x] Vulnerability Disclosure Policy

Documentation
* [x] Per-feature documentation. 
* [ ] Per-item documentation in public API. 
    - Docstrings, not hosted in API Docs.
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Checked with `ament_copyright`
* [x] Quality Declaration document

Testing:
* [x] System tests, which cover "features"
* [x] Tests covering public API
* [x] Code Coverage > 95%:
  - * [x] Must have code coverage tracking for the package -> [here](https://ci.ros2.org/job/ci_linux_coverage/lastSuccessfulBuild/cobertura/)
  - * [x] Must have and enforce a code coverage policy for new changes [Policy](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#code-coverage)
* [ ] Performance tests: not currently available.
* [x] Linters and Static Analysis:
  - * [x] Must have a code style and enforce it.
  - * [x] Must use static analysis tools where applicable: 
  -- See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - None
* [x] non-ROS dependencies are equivalent level 1
    - None

Platform Support
* [x] Supports all tier 1 platforms as described in [REP-2000](https://www.ros.org/reps/rep-2000.html#support-tiers)

**Comment by chapulina** [comment]
It's already level 1: https://github.com/ament/ament_index/pull/66

I don't have the power to close the issue, but it can be closed.
