### ISSUE TITLE
Python get_resource will always succeed when resource_name is an absolute path

### ISSUE THREAD

**Issue by AzaelCicero** [ament/ament_index#72]
Python implementation of get_resource function will always succeed, when passing absolute path to file via resource_name argument. It returns content of the file, and first searched path. 

https://github.com/ament/ament_index/blob/a5631044a837ed3a1844a0a22378139a8430a965/ament_index_python/ament_index_python/resources.py#L22-L49

Issue is in line 38, join operation with last absolute path as last argument will return this last argument.

From my point of view in case of such input, code should throw exception as resource is not located in searched path.

**Comment by audrow** [comment]
Hi @AzaelCicero, I agree with your reasoning here. If you want to open a PR for this, you can @ me for a review or for any help you need.

**Comment by rob-clarke** [comment]
This should be fixed by #69 
Passing an absolute path (or indeed any string containing either `/` or `\`) will result in a new `InvalidResourceName` exception being raised.

**Comment by AzaelCicero** [comment]
I agree with @rob-clarke, work done in #69  is addressing the issue. Therefore this one can be closed as duplicate.
