### ISSUE TITLE
New Foxy/Galactic/Rolling Releases

### ISSUE THREAD

**Issue by DLu** [ament/ament_index#78]
After we close #74, I'd like to get a new new release with all the latest features. I realize the last release was last month, but thought I'd get it on the radar anyway.

**Comment by DLu** [comment]
@audrow Can we get this rolling (pun slightly intended)?

**Comment by audrow** [comment]
Sure, I'll try to make the release tomorrow.

**Comment by audrow** [comment]
I made the releases:
* https://github.com/ros/rosdistro/pull/30078
* https://github.com/ros/rosdistro/pull/30080
* https://github.com/ros/rosdistro/pull/30081

**Comment by DLu** [comment]
:tada:
