### ISSUE TITLE
implement topological order in sh and bat

### ISSUE THREAD

**Issue by dirk-thomas** [ament/ament_index#9]
Then the prefix-level `local_setup` file doesn't need to call Python anymore.

**Comment by dirk-thomas** [comment]
I will close this since:

* the issue is not related to this repo
* it is very unlikely that we will ever implement something complex like topological order in sh / bat

**Comment by wjwwood** [comment]
> the issue is not related to this repo

Well the template for that file is in this package right?

> it is very unlikely that we will ever implement something complex like topological order in sh / bat

But if a contributor wanted to do it then we'd consider the pr no? It might be useful as I think it's one of the last things that makes python an "exec" dependency of `ament_cmake`, i.e. with this change a workspace could be redistributed and used (including sourcing the setup files) without python installed.

For this reason (possibility of future contribution) I left it open and with the label "help wanted".

**Comment by dirk-thomas** [comment]
> Well the template for that file is in this package right?

Is it? Can you post a link to the template? I thought they are in https://github.com/ament/ament_package/tree/master/ament_package/template

> But if a contributor wanted to do it then we'd consider the pr no?

I would rather not maintain that piece of code even if it is contributed...

**Comment by wjwwood** [comment]
> Is it? Can you post a link to the template? I thought they are in https://github.com/ament/ament_package/tree/master/ament_package/template

Oh yeah, this is totally the wrong repo, oops 😛.

> I would rather not maintain that piece of code even if it is contributed...

I suppose, but on the other hand, even the Python code for that has not changed in several years, nor do I expect it to need to do so.
